"""add email verification and password reset tables

Revision ID: 032ee800b301
Revises: remove_valid_until_column
Create Date: 2025-07-21 22:57:58.262915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032ee800b301'
down_revision: Union[str, None] = 'remove_valid_until_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_index(bind, table: str, name: str, columns: list, *, unique: bool) -> None:
    cur = sa.inspect(bind)
    names = {ix['name'] for ix in cur.get_indexes(table)}
    if name not in names:
        op.create_index(name, table, columns, unique=unique)


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if 'email_verifications' not in insp.get_table_names():
        op.create_table(
            'email_verifications',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('token', sa.String(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('is_used', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    _ensure_index(bind, 'email_verifications', op.f('ix_email_verifications_id'), ['id'], unique=False)
    _ensure_index(bind, 'email_verifications', op.f('ix_email_verifications_token'), ['token'], unique=True)
    _ensure_index(bind, 'email_verifications', op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    insp = sa.inspect(bind)
    if 'password_resets' not in insp.get_table_names():
        op.create_table(
            'password_resets',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('token', sa.String(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('is_used', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    _ensure_index(bind, 'password_resets', op.f('ix_password_resets_id'), ['id'], unique=False)
    _ensure_index(bind, 'password_resets', op.f('ix_password_resets_token'), ['token'], unique=True)
    _ensure_index(bind, 'password_resets', op.f('ix_password_resets_user_id'), ['user_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
