"""Add payment_period and auto_renewal to subscriptions

Revision ID: 10f894bb7b08
Revises: simple_salon_notes
Create Date: 2025-09-10 10:53:45.063547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f894bb7b08'
down_revision: Union[str, None] = 'simple_salon_notes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Пропускаем изменение типа owner_type для SQLite совместимости
    # op.alter_column('availability_slots', 'owner_type',
    #            existing_type=sa.VARCHAR(length=6),
    #            type_=sa.Enum('MASTER', 'INDIE_MASTER', 'SALON', name='ownertype'),
    #            existing_nullable=True)
    
    # Создаем индексы только если они не существуют
    try:
        op.create_index('idx_subscription_reservation_subscription', 'subscription_reservations', ['subscription_id'], unique=False)
    except Exception:
        pass  # Индекс уже существует
    
    try:
        op.create_index('idx_subscription_reservation_user', 'subscription_reservations', ['user_id'], unique=False)
    except Exception:
        pass  # Индекс уже существует
    # Добавляем колонки только если они не существуют
    try:
        op.add_column('subscriptions', sa.Column('payment_period', sa.String(), nullable=True))
    except Exception:
        pass  # Колонка уже существует
    
    try:
        op.add_column('subscriptions', sa.Column('auto_renewal', sa.Boolean(), nullable=True))
    except Exception:
        pass  # Колонка уже существует
    # Пропускаем удаление индексов и колонок для совместимости
    # op.drop_index('idx_subscription_end_date', table_name='subscriptions')
    # op.drop_index('idx_subscription_is_active', table_name='subscriptions')
    # op.drop_index('idx_subscription_status', table_name='subscriptions')
    # op.drop_index('idx_subscription_user_type', table_name='subscriptions')
    # op.drop_column('subscriptions', 'updated_at')
    # op.drop_column('subscriptions', 'created_at')
    # op.drop_column('subscriptions', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_method', sa.VARCHAR(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # op.create_index('idx_subscription_user_type', 'subscriptions', ['user_id', 'subscription_type'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_is_active', 'subscriptions', ['is_active'], unique=False)
    op.create_index('idx_subscription_end_date', 'subscriptions', ['end_date'], unique=False)
    op.drop_column('subscriptions', 'payment_period')
    op.drop_index('idx_subscription_reservation_user', table_name='subscription_reservations')
    op.drop_index('idx_subscription_reservation_subscription', table_name='subscription_reservations')
    op.alter_column('availability_slots', 'owner_type',
               existing_type=sa.Enum('MASTER', 'INDIE_MASTER', 'SALON', name='ownertype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
