"""add_website_management_fields_to_salon_branches

Revision ID: 19b2bb2ced93
Revises: f1035797e640
Create Date: 2025-08-16 15:13:30.213160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b2bb2ced93'
down_revision: Union[str, None] = 'f1035797e640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля для управления сайтом филиалов
    op.add_column('salon_branches', sa.Column('url_slug', sa.String(), nullable=True))
    op.add_column('salon_branches', sa.Column('yandex_map_embed', sa.Text(), nullable=True))
    op.add_column('salon_branches', sa.Column('background_color', sa.String(), nullable=True))
    op.add_column('salon_branches', sa.Column('logo_path', sa.String(), nullable=True))
    op.add_column('salon_branches', sa.Column('use_salon_logo', sa.Boolean(), nullable=True))
    
    # Убираем поле background_color из салонов
    op.drop_column('salons', 'background_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем поле background_color в салоны
    op.add_column('salons', sa.Column('background_color', sa.TEXT(), server_default=sa.text("'#ffffff'"), nullable=True))
    
    # Убираем поля управления сайтом из филиалов
    op.drop_column('salon_branches', 'use_salon_logo')
    op.drop_column('salon_branches', 'logo_path')
    op.drop_column('salon_branches', 'background_color')
    op.drop_column('salon_branches', 'yandex_map_embed')
    op.drop_column('salon_branches', 'url_slug')
    # ### end Alembic commands ###
