"""add_client_restrictions_table

Revision ID: 20d3129ef7ad
Revises: 4a3162c37a1c
Create Date: 2025-08-16 16:36:12.420740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3129ef7ad'
down_revision: Union[str, None] = '4a3162c37a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу ограничений клиентов
    op.create_table('client_restrictions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=True),
        sa.Column('indie_master_id', sa.Integer(), nullable=True),
        sa.Column('client_phone', sa.String(), nullable=False),
        sa.Column('restriction_type', sa.Enum('blacklist', 'advance_payment_only', name='restrictiontype'), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['indie_master_id'], ['indie_masters.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы
    op.create_index('idx_client_restriction_salon', 'client_restrictions', ['salon_id'], unique=False)
    op.create_index('idx_client_restriction_indie_master', 'client_restrictions', ['indie_master_id'], unique=False)
    op.create_index('idx_client_restriction_phone', 'client_restrictions', ['client_phone'], unique=False)
    op.create_index('idx_client_restriction_type', 'client_restrictions', ['restriction_type'], unique=False)
    op.create_index('idx_client_restriction_active', 'client_restrictions', ['is_active'], unique=False)
    op.create_index('idx_client_restriction_unique', 'client_restrictions', ['salon_id', 'indie_master_id', 'client_phone', 'restriction_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы
    op.drop_index('idx_client_restriction_unique', table_name='client_restrictions')
    op.drop_index('idx_client_restriction_active', table_name='client_restrictions')
    op.drop_index('idx_client_restriction_type', table_name='client_restrictions')
    op.drop_index('idx_client_restriction_phone', table_name='client_restrictions')
    op.drop_index('idx_client_restriction_indie_master', table_name='client_restrictions')
    op.drop_index('idx_client_restriction_salon', table_name='client_restrictions')
    
    # Удаляем таблицу
    op.drop_table('client_restrictions')
    # ### end Alembic commands ###
