"""create_moderator_permissions_table

Revision ID: 216a65f51252
Revises: 071a4eccd6d9
Create Date: 2025-07-15 19:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216a65f51252'
down_revision: Union[str, None] = '071a4eccd6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = set(insp.get_table_names())
    if 'moderator_permissions' not in tables:
        op.create_table(
            'moderator_permissions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('can_view_users', sa.Boolean(), nullable=True),
            sa.Column('can_edit_users', sa.Boolean(), nullable=True),
            sa.Column('can_delete_users', sa.Boolean(), nullable=True),
            sa.Column('can_ban_users', sa.Boolean(), nullable=True),
            sa.Column('can_view_blog', sa.Boolean(), nullable=True),
            sa.Column('can_create_blog', sa.Boolean(), nullable=True),
            sa.Column('can_edit_blog', sa.Boolean(), nullable=True),
            sa.Column('can_delete_blog', sa.Boolean(), nullable=True),
            sa.Column('can_publish_blog', sa.Boolean(), nullable=True),
            sa.Column('can_view_salons', sa.Boolean(), nullable=True),
            sa.Column('can_edit_salons', sa.Boolean(), nullable=True),
            sa.Column('can_delete_salons', sa.Boolean(), nullable=True),
            sa.Column('can_view_masters', sa.Boolean(), nullable=True),
            sa.Column('can_edit_masters', sa.Boolean(), nullable=True),
            sa.Column('can_delete_masters', sa.Boolean(), nullable=True),
            sa.Column('can_view_bookings', sa.Boolean(), nullable=True),
            sa.Column('can_edit_bookings', sa.Boolean(), nullable=True),
            sa.Column('can_delete_bookings', sa.Boolean(), nullable=True),
            sa.Column('can_view_stats', sa.Boolean(), nullable=True),
            sa.Column('can_view_settings', sa.Boolean(), nullable=True),
            sa.Column('can_edit_settings', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    insp = sa.inspect(bind)
    idx_names = {ix['name'] for ix in insp.get_indexes('moderator_permissions')}
    ix_id = op.f('ix_moderator_permissions_id')
    if ix_id not in idx_names:
        op.create_index(ix_id, 'moderator_permissions', ['id'], unique=False)

    uq_cols = {
        tuple(u['column_names'])
        for u in insp.get_unique_constraints('moderator_permissions')
    }
    if ('user_id',) not in uq_cols:
        op.create_unique_constraint(None, 'moderator_permissions', ['user_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderator_permissions', type_='unique')
    op.drop_index(op.f('ix_moderator_permissions_id'), table_name='moderator_permissions')
    op.drop_table('moderator_permissions')
    # ### end Alembic commands ###
