"""add_expense_management_tables

Revision ID: 2e8aadb81db1
Revises: 20d3129ef7ad
Create Date: 2025-08-16 17:20:54.696617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8aadb81db1'
down_revision: Union[str, None] = '20d3129ef7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу типов расходов
    op.create_table('expense_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=True),
        sa.Column('indie_master_id', sa.Integer(), nullable=True),
        sa.Column('branch_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['salon_branches.id'], ),
        sa.ForeignKeyConstraint(['indie_master_id'], ['indie_masters.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы для типов расходов
    op.create_index('idx_expense_type_branch', 'expense_types', ['branch_id'], unique=False)
    op.create_index('idx_expense_type_indie_master', 'expense_types', ['indie_master_id'], unique=False)
    op.create_index('idx_expense_type_name', 'expense_types', ['name'], unique=False)
    op.create_index('idx_expense_type_salon', 'expense_types', ['salon_id'], unique=False)
    
    # Создаем таблицу шаблонов расходов
    op.create_table('expense_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=True),
        sa.Column('indie_master_id', sa.Integer(), nullable=True),
        sa.Column('branch_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('expense_name', sa.String(), nullable=False),
        sa.Column('expense_type_id', sa.Integer(), nullable=False),
        sa.Column('contractor', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['salon_branches.id'], ),
        sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.id'], ),
        sa.ForeignKeyConstraint(['indie_master_id'], ['indie_masters.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы для шаблонов расходов
    op.create_index('idx_expense_template_branch', 'expense_templates', ['branch_id'], unique=False)
    op.create_index('idx_expense_template_indie_master', 'expense_templates', ['indie_master_id'], unique=False)
    op.create_index('idx_expense_template_name', 'expense_templates', ['name'], unique=False)
    op.create_index('idx_expense_template_salon', 'expense_templates', ['salon_id'], unique=False)
    
    # Создаем таблицу расходов
    op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=True),
        sa.Column('indie_master_id', sa.Integer(), nullable=True),
        sa.Column('branch_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('expense_type_id', sa.Integer(), nullable=False),
        sa.Column('amount_without_vat', sa.Float(), nullable=False),
        sa.Column('amount_with_vat', sa.Float(), nullable=False),
        sa.Column('is_vat_free', sa.Boolean(), nullable=True),
        sa.Column('contractor', sa.String(), nullable=False),
        sa.Column('expense_month', sa.Date(), nullable=False),
        sa.Column('is_recurring', sa.Boolean(), nullable=True),
        sa.Column('recurring_frequency', sa.String(), nullable=True),
        sa.Column('recurring_start_date', sa.Date(), nullable=True),
        sa.Column('recurring_end_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['salon_branches.id'], ),
        sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.id'], ),
        sa.ForeignKeyConstraint(['indie_master_id'], ['indie_masters.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы для расходов
    op.create_index('idx_expense_branch', 'expenses', ['branch_id'], unique=False)
    op.create_index('idx_expense_indie_master', 'expenses', ['indie_master_id'], unique=False)
    op.create_index('idx_expense_month', 'expenses', ['expense_month'], unique=False)
    op.create_index('idx_expense_recurring', 'expenses', ['is_recurring'], unique=False)
    op.create_index('idx_expense_salon', 'expenses', ['salon_id'], unique=False)
    op.create_index('idx_expense_type', 'expenses', ['expense_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы для расходов
    op.drop_index('idx_expense_type', table_name='expenses')
    op.drop_index('idx_expense_salon', table_name='expenses')
    op.drop_index('idx_expense_recurring', table_name='expenses')
    op.drop_index('idx_expense_month', table_name='expenses')
    op.drop_index('idx_expense_indie_master', table_name='expenses')
    op.drop_index('idx_expense_branch', table_name='expenses')
    
    # Удаляем таблицу расходов
    op.drop_table('expenses')
    
    # Удаляем индексы для шаблонов расходов
    op.drop_index('idx_expense_template_salon', table_name='expense_templates')
    op.drop_index('idx_expense_template_name', table_name='expense_templates')
    op.drop_index('idx_expense_template_indie_master', table_name='expense_templates')
    op.drop_index('idx_expense_template_branch', table_name='expense_templates')
    
    # Удаляем таблицу шаблонов расходов
    op.drop_table('expense_templates')
    
    # Удаляем индексы для типов расходов
    op.drop_index('idx_expense_type_salon', table_name='expense_types')
    op.drop_index('idx_expense_type_name', table_name='expense_types')
    op.drop_index('idx_expense_type_indie_master', table_name='expense_types')
    op.drop_index('idx_expense_type_branch', table_name='expense_types')
    
    # Удаляем таблицу типов расходов
    op.drop_table('expense_types')
    # ### end Alembic commands ###
