"""add_subscription_freeze_table

Revision ID: 383f4e3e8235
Revises: acfe03ddc463
Create Date: 2025-12-06 16:09:15.377417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383f4e3e8235'
down_revision: Union[str, None] = 'acfe03ddc463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование таблицы перед созданием
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Создаем таблицу subscription_freezes только если её нет
    if 'subscription_freezes' not in existing_tables:
        op.create_table(
            'subscription_freezes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('freeze_days', sa.Integer(), nullable=False),
        sa.Column('is_cancelled', sa.Boolean(), nullable=True, server_default='0'),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_subscription_freeze_subscription', 'subscription_freezes', ['subscription_id'], unique=False)
        op.create_index('idx_subscription_freeze_dates', 'subscription_freezes', ['start_date', 'end_date'], unique=False)
        op.create_index(op.f('ix_subscription_freezes_id'), 'subscription_freezes', ['id'], unique=False)
    else:
        print("⚠️ Таблица subscription_freezes уже существует, пропускаем создание")
    
    op.create_foreign_key(None, 'bookings', 'users', ['cancelled_by_user_id'], ['id'])
    op.drop_index('ix_client_favorites_id', table_name='client_favorites')
    op.create_index(op.f('ix_client_favorites_client_favorite_id'), 'client_favorites', ['client_favorite_id'], unique=False)
    op.alter_column('client_master_notes', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('client_master_notes', 'rating')
    op.drop_index('idx_master_page_module_master', table_name='master_page_modules')
    op.drop_index('idx_master_page_module_position', table_name='master_page_modules')
    op.drop_index('idx_subscription_addon_active', table_name='subscription_addons')
    op.drop_index('idx_subscription_addon_type', table_name='subscription_addons')
    op.create_unique_constraint(None, 'subscription_addons', ['name'])
    op.drop_index('idx_subscription_plan_active', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_type', table_name='subscription_plans')
    op.create_foreign_key(None, 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    # Удаляем таблицу subscription_freezes
    op.drop_index(op.f('ix_subscription_freezes_id'), table_name='subscription_freezes')
    op.drop_index('idx_subscription_freeze_dates', table_name='subscription_freezes')
    op.drop_index('idx_subscription_freeze_subscription', table_name='subscription_freezes')
    op.drop_table('subscription_freezes')
    op.create_index('idx_subscription_plan_type', 'subscription_plans', ['subscription_type'], unique=False)
    op.create_index('idx_subscription_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.drop_constraint(None, 'subscription_addons', type_='unique')
    op.create_index('idx_subscription_addon_type', 'subscription_addons', ['subscription_type'], unique=False)
    op.create_index('idx_subscription_addon_active', 'subscription_addons', ['is_active'], unique=False)
    op.create_index('idx_master_page_module_position', 'master_page_modules', ['master_id', 'position'], unique=False)
    op.create_index('idx_master_page_module_master', 'master_page_modules', ['master_id'], unique=False)
    op.add_column('client_master_notes', sa.Column('rating', sa.VARCHAR(), nullable=True))
    op.alter_column('client_master_notes', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_client_favorites_client_favorite_id'), table_name='client_favorites')
    op.create_index('ix_client_favorites_id', 'client_favorites', ['client_favorite_id'], unique=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
