"""add_city_and_timezone_to_salon_and_master

Revision ID: 3b2ef651469c
Revises: 216a65f51252
Create Date: 2025-07-18 01:32:55.209418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2ef651469c'
down_revision: Union[str, None] = '216a65f51252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('city', sa.String(), nullable=True))
    op.add_column('masters', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('salons', sa.Column('city', sa.String(), nullable=True))
    op.add_column('salons', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'timezone')
    op.drop_column('salons', 'city')
    op.drop_column('masters', 'timezone')
    op.drop_column('masters', 'city')
    # ### end Alembic commands ###
