"""add_payment_methods_to_salon_and_master

Revision ID: 4a3162c37a1c
Revises: 6732f2b2ea12
Create Date: 2025-08-16 16:04:08.716204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3162c37a1c'
down_revision: Union[str, None] = '6732f2b2ea12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поля для способов оплаты в салоны
    op.add_column('salons', sa.Column('payment_on_visit', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('salons', sa.Column('payment_advance', sa.Boolean(), nullable=True, server_default='0'))
    
    # Добавляем поля для способов оплаты в мастеров-индивидуалов
    op.add_column('indie_masters', sa.Column('payment_on_visit', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('indie_masters', sa.Column('payment_advance', sa.Boolean(), nullable=True, server_default='0'))
    
    # Добавляем поля для оплаты в бронирования
    op.add_column('bookings', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('payment_deadline', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('payment_amount', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('is_paid', sa.Boolean(), nullable=True, server_default='0'))
    
    # Обновляем существующие записи
    op.execute("UPDATE salons SET payment_on_visit = 1, payment_advance = 0 WHERE payment_on_visit IS NULL")
    op.execute("UPDATE indie_masters SET payment_on_visit = 1, payment_advance = 0 WHERE payment_on_visit IS NULL")
    op.execute("UPDATE bookings SET is_paid = 0 WHERE is_paid IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем поля для оплаты из бронирований
    op.drop_column('bookings', 'is_paid')
    op.drop_column('bookings', 'payment_amount')
    op.drop_column('bookings', 'payment_deadline')
    op.drop_column('bookings', 'payment_method')
    
    # Удаляем поля для способов оплаты из мастеров-индивидуалов
    op.drop_column('indie_masters', 'payment_advance')
    op.drop_column('indie_masters', 'payment_on_visit')
    
    # Удаляем поля для способов оплаты из салонов
    op.drop_column('salons', 'payment_advance')
    op.drop_column('salons', 'payment_on_visit')
    # ### end Alembic commands ###
