"""Add master work mode fields

Revision ID: 4c65d5480ce3
Revises: 
Create Date: 2025-06-30 14:59:47.414861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c65d5480ce3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('can_work_independently', sa.Boolean(), nullable=True))
    op.add_column('masters', sa.Column('can_work_in_salon', sa.Boolean(), nullable=True))
    op.add_column('masters', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'website')
    op.drop_column('masters', 'can_work_in_salon')
    op.drop_column('masters', 'can_work_independently')
    # ### end Alembic commands ###
