"""add_calculator_settings_table

Revision ID: 512de4141129
Revises: add_salon_master_service_settings
Create Date: 2025-07-20 19:34:54.690559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512de4141129'
down_revision: Union[str, None] = 'add_salon_master_service_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if 'calculator_settings' not in insp.get_table_names():
        op.create_table(
            'calculator_settings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('salon_base_rate', sa.Integer(), nullable=True),
            sa.Column('salon_branch_pricing', sa.JSON(), nullable=True),
            sa.Column('salon_employee_pricing', sa.JSON(), nullable=True),
            sa.Column('master_base_rate', sa.Integer(), nullable=True),
            sa.Column('master_booking_pricing', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    insp = sa.inspect(bind)
    ix_name = op.f('ix_calculator_settings_id')
    idx_names = {ix['name'] for ix in insp.get_indexes('calculator_settings')}
    if ix_name not in idx_names:
        op.create_index(ix_name, 'calculator_settings', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculator_settings_id'), table_name='calculator_settings')
    op.drop_table('calculator_settings')
    # ### end Alembic commands ###
