"""Update booking statuses and add cancellation fields

Revision ID: 62bed6fe1c6d
Revises: b6752271cbca
Create Date: 2025-10-20 20:23:17.149184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bed6fe1c6d'
down_revision: Union[str, None] = 'b6752271cbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Колонки уже существуют, только обновляем статусы
    op.execute("UPDATE bookings SET status = 'created' WHERE status = 'pending'")
    op.execute("UPDATE bookings SET status = 'completed' WHERE status = 'confirmed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем старые статусы
    op.execute("UPDATE bookings SET status = 'pending' WHERE status = 'created'")
    op.execute("UPDATE bookings SET status = 'confirmed' WHERE status = 'completed'")
    
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_by_user_id')
    # ### end Alembic commands ###
