"""add_client_master_notes_table

Revision ID: 6732f2b2ea12
Revises: 19b2bb2ced93
Create Date: 2025-08-16 15:29:25.030964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6732f2b2ea12'
down_revision: Union[str, None] = '19b2bb2ced93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу для заметок клиентов к мастерам
    op.create_table('client_master_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('master_id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=False),
        sa.Column('note', sa.String(length=400), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы
    op.create_index('idx_client_master_note_client', 'client_master_notes', ['client_id'], unique=False)
    op.create_index('idx_client_master_note_master', 'client_master_notes', ['master_id'], unique=False)
    op.create_index('idx_client_master_note_salon', 'client_master_notes', ['salon_id'], unique=False)
    op.create_index('idx_client_master_note_unique', 'client_master_notes', ['client_id', 'master_id', 'salon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы
    op.drop_index('idx_client_master_note_unique', table_name='client_master_notes')
    op.drop_index('idx_client_master_note_salon', table_name='client_master_notes')
    op.drop_index('idx_client_master_note_master', table_name='client_master_notes')
    op.drop_index('idx_client_master_note_client', table_name='client_master_notes')
    
    # Удаляем таблицу
    op.drop_table('client_master_notes')
    # ### end Alembic commands ###
