"""add_timezone_to_indie_master

Revision ID: 7fadfa330abd
Revises: 83aa1dd21aac
Create Date: 2025-08-27 00:07:51.612332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fadfa330abd'
down_revision: Union[str, None] = '83aa1dd21aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite не поддерживает ALTER COLUMN TYPE, поэтому пропускаем изменение owner_type
    # op.alter_column('availability_slots', 'owner_type',
    #            existing_type=sa.VARCHAR(length=6),
    #            type_=sa.Enum('MASTER', 'INDIE_MASTER', 'SALON', name='ownertype'),
    #            existing_nullable=True)
    op.add_column('indie_masters', sa.Column('city', sa.String(), nullable=True))
    op.add_column('indie_masters', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indie_masters', 'timezone')
    op.drop_column('indie_masters', 'city')
    # SQLite не поддерживает ALTER COLUMN TYPE, поэтому пропускаем изменение owner_type
    # op.alter_column('availability_slots', 'owner_type',
    #            existing_type=sa.Enum('MASTER', 'INDIE_MASTER', 'SALON', name='ownertype'),
    #            type_=sa.VARCHAR(length=6),
    #            existing_nullable=True)
    # ### end Alembic commands ###
