"""add_automation_settings_to_salon_and_master

Revision ID: 83aa1dd21aac
Revises: 63f4fee107cd
Create Date: 2025-08-16 18:09:57.893628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aa1dd21aac'
down_revision: Union[str, None] = '63f4fee107cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля для автоматизации ограничений в таблицу salons
    op.add_column('salons', sa.Column('missed_sessions_advance_payment_threshold', sa.Integer(), nullable=True, server_default='3'))
    op.add_column('salons', sa.Column('missed_sessions_blacklist_threshold', sa.Integer(), nullable=True, server_default='5'))
    op.add_column('salons', sa.Column('cancellation_grace_period_hours', sa.Integer(), nullable=True, server_default='24'))
    
    # Добавляем новые поля для автоматизации ограничений в таблицу indie_masters
    op.add_column('indie_masters', sa.Column('missed_sessions_advance_payment_threshold', sa.Integer(), nullable=True, server_default='3'))
    op.add_column('indie_masters', sa.Column('missed_sessions_blacklist_threshold', sa.Integer(), nullable=True, server_default='5'))
    op.add_column('indie_masters', sa.Column('cancellation_grace_period_hours', sa.Integer(), nullable=True, server_default='24'))
    
    # Обновляем существующие записи значениями по умолчанию
    op.execute("UPDATE salons SET missed_sessions_advance_payment_threshold = 3, missed_sessions_blacklist_threshold = 5, cancellation_grace_period_hours = 24")
    op.execute("UPDATE indie_masters SET missed_sessions_advance_payment_threshold = 3, missed_sessions_blacklist_threshold = 5, cancellation_grace_period_hours = 24")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем поля из таблицы indie_masters
    op.drop_column('indie_masters', 'cancellation_grace_period_hours')
    op.drop_column('indie_masters', 'missed_sessions_blacklist_threshold')
    op.drop_column('indie_masters', 'missed_sessions_advance_payment_threshold')
    
    # Удаляем поля из таблицы salons
    op.drop_column('salons', 'cancellation_grace_period_hours')
    op.drop_column('salons', 'missed_sessions_blacklist_threshold')
    op.drop_column('salons', 'missed_sessions_advance_payment_threshold')
    # ### end Alembic commands ###
