"""Add master expenses and booking confirmations tables

Revision ID: 9d61976d31ea
Revises: 20250127_add_updated_at
Create Date: 2025-10-14 19:06:21.763353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d61976d31ea'
down_revision: Union[str, None] = '20250127_add_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indie_masters', 'can_work_independently')
    op.drop_column('indie_masters', 'updated_at')
    op.drop_column('indie_masters', 'is_active')
    op.add_column('moderator_permissions', sa.Column('can_create_promo_codes', sa.Boolean(), nullable=True))
    op.add_column('moderator_permissions', sa.Column('can_view_promo_codes', sa.Boolean(), nullable=True))
    op.add_column('moderator_permissions', sa.Column('can_edit_promo_codes', sa.Boolean(), nullable=True))
    op.add_column('moderator_permissions', sa.Column('can_delete_promo_codes', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_permissions', 'can_delete_promo_codes')
    op.drop_column('moderator_permissions', 'can_edit_promo_codes')
    op.drop_column('moderator_permissions', 'can_view_promo_codes')
    op.drop_column('moderator_permissions', 'can_create_promo_codes')
    op.add_column('indie_masters', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.add_column('indie_masters', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('indie_masters', sa.Column('can_work_independently', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###
