"""add_phone_verification_fields_only

Revision ID: add_phone_verification_only
Revises: 032ee800b301
Create Date: 2025-07-22 15:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_phone_verification_only'
down_revision: Union[str, None] = '032ee800b301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_code')
    op.drop_column('users', 'phone_verification_expires')
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'is_phone_verified')
    # ### end Alembic commands ### 