"""add_subscription_price_snapshot_table

Revision ID: b6fe42368ede
Revises: 757589d7d340
Create Date: 2025-12-07 12:28:37.571274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fe42368ede'
down_revision: Union[str, None] = '757589d7d340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('price_1month', sa.Float(), nullable=False),
    sa.Column('price_3months', sa.Float(), nullable=False),
    sa.Column('price_6months', sa.Float(), nullable=False),
    sa.Column('price_12months', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('daily_price', sa.Float(), nullable=False),
    sa.Column('reserved_balance', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('upgrade_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_expires', 'subscription_price_snapshots', ['expires_at'], unique=False)
    op.create_index('idx_snapshot_user_created', 'subscription_price_snapshots', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_subscription_price_snapshots_id'), 'subscription_price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_price_snapshots_user_id'), 'subscription_price_snapshots', ['user_id'], unique=False)
    # Пропускаем создание foreign key для bookings.cancelled_by_user_id, так как это не относится к этой миграции
    op.drop_index('ix_client_favorites_id', table_name='client_favorites')
    op.create_index(op.f('ix_client_favorites_client_favorite_id'), 'client_favorites', ['client_favorite_id'], unique=False)
    op.alter_column('client_master_notes', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('client_master_notes', 'rating')
    op.drop_index('idx_master_page_module_master', table_name='master_page_modules')
    op.drop_index('idx_master_page_module_position', table_name='master_page_modules')
    op.drop_index('idx_subscription_plan_active', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_type', table_name='subscription_plans')
    op.create_foreign_key(None, 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_index('idx_subscription_plan_type', 'subscription_plans', ['subscription_type'], unique=False)
    op.create_index('idx_subscription_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('idx_master_page_module_position', 'master_page_modules', ['master_id', 'position'], unique=False)
    op.create_index('idx_master_page_module_master', 'master_page_modules', ['master_id'], unique=False)
    op.add_column('client_master_notes', sa.Column('rating', sa.VARCHAR(), nullable=True))
    op.alter_column('client_master_notes', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_client_favorites_client_favorite_id'), table_name='client_favorites')
    op.create_index('ix_client_favorites_id', 'client_favorites', ['client_favorite_id'], unique=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_price_snapshots_user_id'), table_name='subscription_price_snapshots')
    op.drop_index(op.f('ix_subscription_price_snapshots_id'), table_name='subscription_price_snapshots')
    op.drop_index('idx_snapshot_user_created', table_name='subscription_price_snapshots')
    op.drop_index('idx_snapshot_expires', table_name='subscription_price_snapshots')
    op.drop_table('subscription_price_snapshots')
    # Пропускаем удаление foreign key для bookings.cancelled_by_user_id
    # ### end Alembic commands ###
