"""add_client_salon_notes_table

Revision ID: simple_salon_notes
Revises: 7fadfa330abd
Create Date: 2025-08-31 01:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'simple_salon_notes'
down_revision: Union[str, None] = '7fadfa330abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу для заметок клиентов о салонах
    op.create_table('client_salon_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('salon_id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=True),
        sa.Column('note', sa.String(length=400), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
        sa.ForeignKeyConstraint(['branch_id'], ['salon_branches.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем индексы
    op.create_index('idx_client_salon_note_client', 'client_salon_notes', ['client_id'], unique=False)
    op.create_index('idx_client_salon_note_salon', 'client_salon_notes', ['salon_id'], unique=False)
    op.create_index('idx_client_salon_note_branch', 'client_salon_notes', ['branch_id'], unique=False)
    op.create_index('idx_client_salon_note_unique', 'client_salon_notes', ['client_id', 'salon_id', 'branch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы
    op.drop_index('idx_client_salon_note_unique', table_name='client_salon_notes')
    op.drop_index('idx_client_salon_note_branch', table_name='client_salon_notes')
    op.drop_index('idx_client_salon_note_salon', table_name='client_salon_notes')
    op.drop_index('idx_client_salon_note_client', table_name='client_salon_notes')
    
    # Удаляем таблицу
    op.drop_table('client_salon_notes')
    # ### end Alembic commands ###

