// Список городов России с таймзонами
// Москва и Санкт-Петербург в начале, остальные отсортированы по алфавиту
export const cities = [
  { name: 'Москва', timezone: 'Europe/Moscow' },
  { name: 'Санкт-Петербург', timezone: 'Europe/Moscow' },
  { name: 'Абакан', timezone: 'Asia/Krasnoyarsk' },
  { name: 'Арзамас', timezone: 'Europe/Moscow' },
  { name: 'Армавир', timezone: 'Europe/Moscow' },
  { name: 'Архангельск', timezone: 'Europe/Moscow' },
  { name: 'Астрахань', timezone: 'Europe/Moscow' },
  { name: 'Балаково', timezone: 'Europe/Saratov' },
  { name: 'Балашиха', timezone: 'Europe/Moscow' },
  { name: 'Барнаул', timezone: 'Asia/Barnaul' },
  { name: 'Белгород', timezone: 'Europe/Moscow' },
  { name: 'Бердск', timezone: 'Asia/Novosibirsk' },
  { name: 'Бийск', timezone: 'Asia/Barnaul' },
  { name: 'Благовещенск', timezone: 'Asia/Yakutsk' },
  { name: 'Владивосток', timezone: 'Asia/Vladivostok' },
  { name: 'Владикавказ', timezone: 'Europe/Moscow' },
  { name: 'Владимир', timezone: 'Europe/Moscow' },
  { name: 'Волгоград', timezone: 'Europe/Moscow' },
  { name: 'Вологда', timezone: 'Europe/Moscow' },
  { name: 'Волжский', timezone: 'Europe/Moscow' },
  { name: 'Воронеж', timezone: 'Europe/Moscow' },
  { name: 'Дзержинск', timezone: 'Europe/Moscow' },
  { name: 'Димитровград', timezone: 'Europe/Samara' },
  { name: 'Долгопрудный', timezone: 'Europe/Moscow' },
  { name: 'Домодедово', timezone: 'Europe/Moscow' },
  { name: 'Екатеринбург', timezone: 'Asia/Yekaterinburg' },
  { name: 'Жуковский', timezone: 'Europe/Moscow' },
  { name: 'Златоуст', timezone: 'Asia/Yekaterinburg' },
  { name: 'Ижевск', timezone: 'Europe/Samara' },
  { name: 'Иркутск', timezone: 'Asia/Irkutsk' },
  { name: 'Йошкар-Ола', timezone: 'Europe/Moscow' },
  { name: 'Казань', timezone: 'Europe/Moscow' },
  { name: 'Калининград', timezone: 'Europe/Kaliningrad' },
  { name: 'Каменск-Уральский', timezone: 'Asia/Yekaterinburg' },
  { name: 'Кемерово', timezone: 'Asia/Novokuznetsk' },
  { name: 'Киров', timezone: 'Europe/Moscow' },
  { name: 'Климовск', timezone: 'Europe/Moscow' },
  { name: 'Коломна', timezone: 'Europe/Moscow' },
  { name: 'Комсомольск-на-Амуре', timezone: 'Asia/Vladivostok' },
  { name: 'Кострома', timezone: 'Europe/Moscow' },
  { name: 'Краснодар', timezone: 'Europe/Moscow' },
  { name: 'Красногорск', timezone: 'Europe/Moscow' },
  { name: 'Красноярск', timezone: 'Asia/Krasnoyarsk' },
  { name: 'Курган', timezone: 'Asia/Yekaterinburg' },
  { name: 'Курск', timezone: 'Europe/Moscow' },
  { name: 'Лобня', timezone: 'Europe/Moscow' },
  { name: 'Люберцы', timezone: 'Europe/Moscow' },
  { name: 'Магнитогорск', timezone: 'Asia/Yekaterinburg' },
  { name: 'Майкоп', timezone: 'Europe/Moscow' },
  { name: 'Махачкала', timezone: 'Europe/Moscow' },
  { name: 'Мурманск', timezone: 'Europe/Moscow' },
  { name: 'Мытищи', timezone: 'Europe/Moscow' },
  { name: 'Набережные Челны', timezone: 'Europe/Moscow' },
  { name: 'Нальчик', timezone: 'Europe/Moscow' },
  { name: 'Находка', timezone: 'Asia/Vladivostok' },
  { name: 'Нефтеюганск', timezone: 'Asia/Yekaterinburg' },
  { name: 'Нижневартовск', timezone: 'Asia/Yekaterinburg' },
  { name: 'Нижнекамск', timezone: 'Europe/Moscow' },
  { name: 'Нижний Новгород', timezone: 'Europe/Moscow' },
  { name: 'Новокузнецк', timezone: 'Asia/Novokuznetsk' },
  { name: 'Новороссийск', timezone: 'Europe/Moscow' },
  { name: 'Новосибирск', timezone: 'Asia/Novosibirsk' },
  { name: 'Новочебоксарск', timezone: 'Europe/Moscow' },
  { name: 'Ногинск', timezone: 'Europe/Moscow' },
  { name: 'Норильск', timezone: 'Asia/Krasnoyarsk' },
  { name: 'Одинцово', timezone: 'Europe/Moscow' },
  { name: 'Оренбург', timezone: 'Asia/Yekaterinburg' },
  { name: 'Орёл', timezone: 'Europe/Moscow' },
  { name: 'Орск', timezone: 'Asia/Yekaterinburg' },
  { name: 'Орехово-Зуево', timezone: 'Europe/Moscow' },
  { name: 'Пенза', timezone: 'Europe/Moscow' },
  { name: 'Пермь', timezone: 'Asia/Yekaterinburg' },
  { name: 'Петрозаводск', timezone: 'Europe/Moscow' },
  { name: 'Петропавловск-Камчатский', timezone: 'Asia/Kamchatka' },
  { name: 'Подольск', timezone: 'Europe/Moscow' },
  { name: 'Прокопьевск', timezone: 'Asia/Novokuznetsk' },
  { name: 'Псков', timezone: 'Europe/Moscow' },
  { name: 'Раменское', timezone: 'Europe/Moscow' },
  { name: 'Реутов', timezone: 'Europe/Moscow' },
  { name: 'Ростов-на-Дону', timezone: 'Europe/Moscow' },
  { name: 'Рубцовск', timezone: 'Asia/Barnaul' },
  { name: 'Рыбинск', timezone: 'Europe/Moscow' },
  { name: 'Рязань', timezone: 'Europe/Moscow' },
  { name: 'Самара', timezone: 'Europe/Samara' },
  { name: 'Саранск', timezone: 'Europe/Moscow' },
  { name: 'Саратов', timezone: 'Europe/Saratov' },
  { name: 'Севастополь', timezone: 'Europe/Moscow' },
  { name: 'Северодвинск', timezone: 'Europe/Moscow' },
  { name: 'Сергиев Посад', timezone: 'Europe/Moscow' },
  { name: 'Серпухов', timezone: 'Europe/Moscow' },
  { name: 'Смоленск', timezone: 'Europe/Moscow' },
  { name: 'Сочи', timezone: 'Europe/Moscow' },
  { name: 'Ставрополь', timezone: 'Europe/Moscow' },
  { name: 'Старый Оскол', timezone: 'Europe/Moscow' },
  { name: 'Стерлитамак', timezone: 'Asia/Yekaterinburg' },
  { name: 'Сургут', timezone: 'Asia/Yekaterinburg' },
  { name: 'Сызрань', timezone: 'Europe/Samara' },
  { name: 'Сыктывкар', timezone: 'Europe/Moscow' },
  { name: 'Таганрог', timezone: 'Europe/Moscow' },
  { name: 'Томск', timezone: 'Asia/Tomsk' },
  { name: 'Тольятти', timezone: 'Europe/Samara' },
  { name: 'Тула', timezone: 'Europe/Moscow' },
  { name: 'Тюмень', timezone: 'Asia/Yekaterinburg' },
  { name: 'Улан-Удэ', timezone: 'Asia/Irkutsk' },
  { name: 'Ульяновск', timezone: 'Europe/Samara' },
  { name: 'Уссурийск', timezone: 'Asia/Vladivostok' },
  { name: 'Уфа', timezone: 'Asia/Yekaterinburg' },
  { name: 'Хабаровск', timezone: 'Asia/Vladivostok' },
  { name: 'Химки', timezone: 'Europe/Moscow' },
  { name: 'Чебоксары', timezone: 'Europe/Moscow' },
  { name: 'Челябинск', timezone: 'Asia/Yekaterinburg' },
  { name: 'Череповец', timezone: 'Europe/Moscow' },
  { name: 'Чита', timezone: 'Asia/Chita' },
  { name: 'Шахты', timezone: 'Europe/Moscow' },
  { name: 'Щёлково', timezone: 'Europe/Moscow' },
  { name: 'Электросталь', timezone: 'Europe/Moscow' },
  { name: 'Энгельс', timezone: 'Europe/Saratov' },
  { name: 'Южно-Сахалинск', timezone: 'Asia/Sakhalin' },
  { name: 'Якутск', timezone: 'Asia/Yakutsk' },
  { name: 'Ярославль', timezone: 'Europe/Moscow' }
]

// Функция для получения таймзоны по городу
export const getTimezoneByCity = (cityName) => {
  const city = cities.find(c => c.name === cityName)
  return city ? city.timezone : 'Europe/Moscow'
}

// Функция для получения города по таймзоне
export const getCityByTimezone = (timezone) => {
  const city = cities.find(c => c.timezone === timezone)
  return city ? city.name : 'Москва'
}

// Функция для получения списка городов для выпадающего списка
export const getCitiesOptions = () => {
  return cities.map(city => ({
    value: city.name,
    label: city.name
  }))
} 