name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Create project directory
          mkdir -p /home/root/appointo
          cd /home/root/appointo
          
          # Stop existing containers
          docker-compose -f docker-compose.prod.yml down || true
          
          # Clean up old images
          docker system prune -f || true
        EOF
        
        # Copy files to server
        sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -r . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/root/appointo/
        
        # Deploy on server
        sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/root/appointo
          
          # Build and start containers
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml up -d
          
          # Clean up
          docker system prune -f
          
          echo "Deployment completed!"
        EOF
        
    - name: Health check
      run: |
        sleep 30
        curl -f http://${{ secrets.SERVER_HOST }}/health || exit 1 