name: Docs CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./docs.sh init
      - run: ./docs.sh ci
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site 